name: Deploy to Oracle VM

on:
  push:
    branches:
      - main  # or the branch you use for production

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Pull latest changes
      run: |
        cd /home/ubuntu/clusterWebLab  # replace with the name of your folder
        git pull origin main

    - name: Restart Gunicorn service
      run: |
        sudo systemctl daemon-reexec
        sudo systemctl daemon-reload
        sudo systemctl restart flaskapp
        sudo systemctl status flaskapp
